# -*- coding: utf-8 -*-
"""Copy of test_ensemble.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hXMlt5PAynYdps5D6DP1_q2eDtWyEIX5
"""
#%%

import os
from typing import List

import numpy as np
import pandas as pd

from Bio import SeqIO

import torch
import torch.nn as nn
import matplotlib
from matplotlib import pyplot as plt
import seaborn as sns
import sys 
project_root = 'porter6/predictor3'
if project_root not in sys.path:
    sys.path.append(project_root)

from sklearn import metrics
from torch import optim
from torch.utils.data import DataLoader

# from dataset.domainLinker_dataset import DomainLinkerDataset, Sequence, collate_fn
# from dataset.utils import read_plm

from utils.common import dump_list2json, read_json2list
import params.filePath as paramF
import params.hyperparams_cbrcnn as paramH

import json


from model.utils import load_model, batch_acc, batch_auc
# from utils.static import type_dataset
from utils.ensemble import generate_models, ensemble_predict, ensemble_predict_new

"""# Functions"""

# 1. generate prediction label (not using)
def get_pred_label(pred, threshold=0.1):
    '''
    params:
        pred - predicted list
        label - ground truth
        threshold - better to set the threshold which make the precision similar to recall. (a higher F1 score.)
    return:
        pred_label - list, classification label generate from pred given threshold
    '''
    pred_label = [1 if i>threshold else 0 for i in pred]

    return pred_label

def get_idrIdx(pred_label):
    '''
    pdb atom index: _atom_site.label_seq_id (not author index)
    '''
    return [i+1 for i, e in enumerate(pred_label) if e == 1]

# 4. find index based on entity id
# def get_idxByID(entity_id):
#     for idx, entity in enumerate(list_test_entity):
#         if entity_id==entity['id']:
#             return idx

"""# 1. Predictors"""

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Using device:', device)

#esm&msa_transformer: https://github.com/facebookresearch/esm
featureType_list = ['onehot', 'protTrans', 'esm2']
featureType = featureType_list[2]
net_type = 'cbrcnn' # cbrcnn

netName = f'model.cbrcnn_stage1'
model_name = f'{netName[6:]}'

if featureType=='protTrans':
    n_features = 1024
elif featureType=='esm2':
    n_features = 1280
elif featureType=='onehot':
    n_features = 21

k_folds = 5

folder_model =  'porter6/predictor3/output/trained_model/esm2'

list_modelInfo = [{'model_name':model_name, 'fold': f'_f{k}', 'net_name': netName, 'net_type': net_type, 'lr':paramH.lr, 'dropout':paramH.dropout, 'featureType': featureType, 'model_pth': os.path.join(folder_model, f'{model_name}_f{k}.pth')}  for k in range(1, 6)]
models_P = generate_models(list_modelInfo)

"""# 2. Prediction: Test set

## 2.1. dataset
"""
test = sys.argv[1]#/home/runfeng/Dropbox/flow_topo/data/test_data/test.json
list_entity = read_json2list(f'{test}')
"""## 2.2. prediction"""
j_out = sys.argv[2]
path_pred_caid = f'{j_out}/test_out.json'

list_predInfo = []
list_seq_id = []
print(len(list_entity))
esm_out = sys.argv[3]
paramF.path_features = os.path.dirname(esm_out)
for entity in list_entity:
    entity_id = entity['id']
    # print(entity_id)
    
    if not os.path.exists(f'{esm_out}/{entity_id}.npy'):
        continue
    #entity_length = entity['length']
    # get prediction
    # print(entity_id)
    avg_pred = ensemble_predict_new(models_P, list_modelInfo, entity_id)

    predInfo = {'id': entity_id,   'true_pred': avg_pred.tolist()}
    list_predInfo.append(predInfo)
dump_list2json(list_predInfo, path_pred_caid)
pss = sys.argv[4]

os.system(f'python json2csv3.py {j_out}/test_out.json {pss}')


# %%
